### PR TITLE
Update to Swift 5, add Accio support & make more customizable

### PR DESCRIPTION
**Pull request by Jeehut**
This adds support for SwiftPM manifest based dependency managers. Specifically this adds support for installing via [Accio](https://github.com/JamitLabs/Accio) but will probably also work with SwiftPM once it's integrated into Xcode.

Also this is based on @valerianb fork, therefore adds Swift 5 support. (#37)

Additionally, this adds more customization options added by @jamitJona [here](https://github.com/jamitJona/ChromaColorPicker/commit/54259bb5b42db98fcf8a6912eca0d3391bc31018).

### CODE REVIEW

**Comment by joncardasis** [comment]
@Dschee Any movement on addressing these changes?

**Comment by Dschee** [comment]
What changes do you mean by "these"? The conflict?

**Comment by joncardasis** [comment]
@Jeehut The comments I added on the PR. Can you comment on them/refactor as needed?

**Comment by Jeehut** [comment]
@joncardasis I don't see any comments on the PR.

**Pull request closed without merging**
