### PR TITLE
Swift 4 updates

### PR DESCRIPTION
**Pull request by cloke**
Update project for xCode 9 and swift 4. Silence most deprication warnings.

### CODE REVIEW

**Comment by jugutier** [comment]
Awesome! I was just about to do the same PR. Thanks 🥇

**Comment by V-FEXrt** [comment]
@joncardasis Could you check this out when you have time?

**Comment by jugutier** [comment]
Hi @joncardasis thanks for looking into this PR, could you please also submit an updated pod version? Thx :)

**Comment by joncardasis** [comment]
@jugutier Pushing an updated pod as we speak

**Pull request merged**
